name: mmine
description: "A Flutter-based music player application focused on lossless audio format playback."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  audio_service: 0.18.18
  audio_session: 0.2.2
  bloc: 9.2.0
  bloc_concurrency: 0.3.0
  cupertino_icons: 1.0.8
  dartz: 0.10.1
  drift: 2.30.1
  equatable: 2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_media_metadata: 1.0.0+1
  freezed_annotation: 3.1.0
  just_audio: 0.10.5
  package_info_plus: 8.1.2
  path: 1.9.1
  path_provider: 2.1.5
  permission_handler: 12.0.1
  sqlite3_flutter_libs: 0.5.41
  uuid: 4.5.2

dev_dependencies:
  build_runner: 2.10.5
  drift_dev: 2.30.1
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.3
  mockito: 5.6.3

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
